# Generated by Django 5.0.6 on 2024-06-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagebooking',
            name='user',
        ),
    ]
