# Generated by Django 5.0.6 on 2024-06-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_packagebooking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagebooking',
            old_name='booking_studio',
            new_name='booking_status',
        ),
    ]
