# Generated by Django 5.0.6 on 2024-06-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_booking_studio_packagebooking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainbooking',
            name='train',
        ),
        migrations.RemoveField(
            model_name='trainbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='TrainBooking',
        ),
    ]
